# Balancing the dataset

### 2-Techniques: \<Up Sampling> and \<Down Sampling>

In [3]:
import numpy as np
import pandas as pd

np.random.seed(456)

n_samples = 1000
class_0_ratio = 0.9
n_class_0=int(n_samples*class_0_ratio)
n_class_1 = round(n_samples*(1-class_0_ratio))
(n_class_0,n_class_1)

(900, 100)

In [4]:
#Creating the data frame

class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})
class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [5]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [6]:
df.head()

   feature_1  feature_2  target
0  -0.668129   0.378859       0
1  -0.498210  -0.767022       0
2   0.618576   0.720510       0
3   0.568692   0.363712       0
4   1.350509   0.045913       0

In [7]:
df.tail()

     feature_1  feature_2  target
995   1.421099  -0.573522       1
996  -1.446118   1.739478       1
997   1.855054   0.327192       1
998  -0.616961   0.020510       1
999   0.995837  -0.563858       1

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [9]:
df_minority=df[df['target']==1]
df_majority=df[df['target'] ==0]

In [10]:
from sklearn.utils import resample

df_minority_upsampled= resample(df_minority,replace=True,
                                n_samples=len(df_majority),
                                random_state=42)

In [11]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951  -0.195966   0.435854       1
992   0.644822  -1.836403       1
914   1.629236  -0.242322       1
971  -0.388595   0.215994       1
960   0.884386  -0.001006       1

### After upsampling datapoints increased from 100 to 900

In [ ]:
df_minority_upsampled.shape

(900, 3)

In [16]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])
df_upsampled.shape

(1800, 3)

In [17]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [18]:
df_minority=df[df['target']==1]
df_majority=df[df['target'] ==0]

In [19]:
df_majority_downsampled= resample(df_majority,replace=False,
                                n_samples=len(df_minority),
                                random_state=42)

In [20]:
df_majority_downsampled.shape

(100, 3)

In [22]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64